version: "3.8"
services:
    postgres:
        image: postgres
        ports:
          - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: todolist
    kurento:
        image: kurento/kurento-media-server
        ports:
          - 8888:8888
