version: "3.8"
services:
    postgres:
        image: postgres
        ports:
          - 5432:5432
        environment:
            POSTGRES_USER: streamflow_user
            POSTGRES_PASSWORD: streamflow_password
            POSTGRES_DB: streamflow
    kurento:
        image: kurento/kurento-media-server
        ports:
          - 8888:8888
